parameters:

  assets_backup.class:       dmAssetsBackup
  assets_backup.adapter:     dmAssetsBackupAdapterTar
  assets_backup.options:
    backup_dir:              SF_ROOT_DIR/data/dm/backup/assets
    source_dir:              SF_UPLOAD_DIR

services:

  assets_backup:
    class:                %assets_backup.class%
    shared:               false
    arguments:            [ @filesystem, %assets_backup.adapter%, %assets_backup.options% ]