parameters:

  assets_backup.class:       dmAssetsBackup
  assets_backup.adapters:
    tar:                dmAssetsBackupAdapterTar
  assets_backup.options:
    dir:                  SF_ROOT_DIR/data/dm/backup/assets
    file_format:          %%year%%-%%month%%-%%day%%-%%time%%

services:

  assets_backup:
    class:                %assets_backup.class%
    shared:               false
    arguments:            [ @filesystem, %assets_backup.adapters%, %assets_backup.options% ]